# Test pandas_cub manually

In this notebook, we will test pandas_cub manually.

In [5]:
import sys
sys.executable

'C:\\Users\\Feras\\Anaconda3\\envs\\pandas_cub\\python.exe'

In [6]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [7]:
import numpy as np
import pandas_cub as pdc
import pandas_cub_final as pdcf
import pandas as pd

In [8]:
name = np.array(['Penelope', 'Niko', 'Eleni'])
state = np.array(['Texas', 'California', 'Texas'])
height = np.array([3.6, 3.5, 5.2])
school = np.array([True, False, True])
weight = np.array([45, 40, 130])

data = {'name': name, 'state': state, 'height': height, 
        'school': school, 'weight': weight}

df = pdc.DataFrame(data)
df_final = pdcf.DataFrame(data)
df_pandas = pd.DataFrame(data)

In [9]:
df

In [10]:
df_final

In [11]:
df_pandas

name       state  height  school  weight
0  Penelope       Texas     3.6    True      45
1      Niko  California     3.5   False      40
2     Eleni       Texas     5.2    True     130

In [12]:
data = {'ones':np.array([1,1,1]), 'twos':np.array([2,2,2])}

In [13]:
df_pandas['state']

0         Texas
1    California
2         Texas
Name: state, dtype: object

In [17]:
df['state']

In [16]:
df_pandas[['state','school']]

state  school
0       Texas    True
1  California   False
2       Texas    True

In [18]:
df[['state','school']]

In [19]:
df['school']

In [50]:
df[df['school']]

TypeError: 'numpy.ndarray' object is not callable

In [34]:
list(data.keys())

['ones', 'twos']

In [38]:
arr = data['ones']; arr

array([1, 1, 1])

In [39]:
arr[[True, True, False]]

array([1, 1])

In [41]:
list(data.values())

[array([1, 1, 1]), array([2, 2, 2])]

In [49]:
next(iter(list(data.values())))

array([1, 1, 1])

In [51]:
d1 = {'i':np.array([1,1,1])}

In [52]:
d1

{'i': array([1, 1, 1])}

In [55]:
d1.values

<function dict.values>

In [56]:
df.values

array([['Penelope', 'Texas', 3.6, True, 45],
       ['Niko', 'California', 3.5, False, 40],
       ['Eleni', 'Texas', 5.2, True, 130]], dtype=object)