# Test pandas_cub manually

In this notebook, we will test pandas_cub manually.

In [1]:
import sys
sys.executable

'C:\\Users\\Admin\\Anaconda3\\envs\\pandas_cub\\python.exe'

In [2]:
%load_ext autoreload
%autoreload 2

In [3]:
import numpy as np
import pandas_cub as pdc
import pandas_cub_final as pdcf
import pandas as pd

In [4]:
name = np.array(['Penelope', 'Niko', 'Eleni'])
state = np.array(['Texas', 'California', 'Texas'])
height = np.array([3.6, 3.5, 5.2])
school = np.array([True, False, True])
weight = np.array([45, 40, 130])

data = {'name': name, 'state': state, 'height': height, 
        'school': school, 'weight': weight}

df = pdc.DataFrame(data)
df_final = pdcf.DataFrame(data)
df_pandas = pd.DataFrame(data)

In [5]:
df

In [6]:
df_final

In [7]:
df_pandas

name       state  height  school  weight
0  Penelope       Texas     3.6    True      45
1      Niko  California     3.5   False      40
2     Eleni       Texas     5.2    True     130

In [8]:
data = {'ones':np.array([1,1,1]), 'twos':np.array([2,2,2])}

In [10]:
d1 = {'ones':np.array([1,1,1])}

In [14]:
a = next(iter(list(d1.values())))

In [15]:
b = [True, True, False]

In [16]:
a[b]

array([1, 1])

In [17]:
dd = df['school']

In [20]:
dd.values.reshape(-1)

array([ True, False,  True])

In [66]:
d = df['school']

In [67]:
d

In [24]:
d.values.reshape(-1)

array([ True, False,  True])

In [29]:
for kay, val in data.items():
    print(val)

[1 1 1]
[2 2 2]


In [68]:
c = df[d]

In [69]:
c

In [70]:
type(d)

pandas_cub.DataFrame

In [47]:
d.values.reshape(-1)

array([ True, False,  True])

In [53]:
next(iter(list(d._data.values())))

array([ True, False,  True])

In [ ]:
df['school']